version: '3.5'
services:
    user-db:
        image: mysql:5.7.22
        command: --default-authentication-plugin=mysql_native_password
        container_name: user_db
        environment:
            - MYSQL_ROOT_PASSWORD=test
            - MYSQL_DATABASE=user_db
        # ports:
        #     - "3306:3306"
        deploy:
            restart_policy:
                condition: on-failure
        networks:
            backend-network:
                ipv4_address: "192.168.1.100"
    bidding-db:
        image: mysql:5.7.22
        command: --default-authentication-plugin=mysql_native_password
        container_name: bidding_db
        environment:
            - MYSQL_ROOT_PASSWORD=test
            - MYSQL_DATABASE=bidding_db
        # ports:
        #     - "3306:3306"
        deploy:
            restart_policy:
                condition: on-failure
        networks:
            backend-network:
                ipv4_address: "192.168.1.101"
    bidding-ms:
        image: bidding-service
        build:
            context: ./bidding_service
        container_name: bidding_service
        depends_on:
            - bidding-db
        ports:
            - "8083:9002"
        networks:
            backend-network:
                ipv4_address: "192.168.1.102"
        deploy:
            restart_policy:
                condition: on-failure
        environment:
            - LC_ALL=C.UTF-8
            - LANG=C.UTF-8
            - OPENAPI_URL=""
            - MYSQL_ROOT_PASSWORD=test
            - MYSQL_DATABASE=bidding_db
            - USER_SERVICE_API=http://192.168.1.103:9002
            - MYSQL_IP_ADDRESS=192.168.1.101
    user-ms:
        image: user-service
        build:
            context: ./user_service
        container_name: user_service
        depends_on:
            - user-db
        ports:
            - "8082:9002"
        networks:
            backend-network:
                ipv4_address: "192.168.1.103"
        deploy:
            restart_policy:
                condition: on-failure
        environment:
            - LC_ALL=C.UTF-8
            - LANG=C.UTF-8
            - OPENAPI_URL=""
            - MYSQL_ROOT_PASSWORD=test
            - MYSQL_DATABASE=user_db
            - MYSQL_IP_ADDRESS=192.168.1.100
networks:
    backend-network:
        ipam:
            driver: default
            config:
                - subnet: 192.168.1.0/24
